---
name: Latest dev.to Articles
on:
  schedule:
    # Runs every hour
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  update-readme-with-articles:
    name: Update this repo's README with latest articles from dev.to
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "ARTICLES-POST-LIST"
          feed_list: "https://dev.to/feed/ragnarkon"
